### ISSUE TITLE
Time is the one cached on the first require

### ISSUE THREAD

**Issue by ramidzkh** [jrmcintyre/time#1]
The time used is from when the package was first required, then it is cached.

## Cause
[Here](https://github.com/jrmcintyre/time/blob/master/index.js#L1)

## Reproduction
```js
const {getDate, getTime} = require('@jrmcintyre/time');
console.log({ date: getDate(), time: getTime() });

setTimeout(() => console.log({ date: getDate(), time: getTime() }), 5000);
```

## Expected behaviour
The time should change every time the methods are called.

**Comment by jrmcintyre** [comment]
Don't worry already fixed
